import type { ARProject } from "../types/project";
import { cameraErrorMessage, requestCameraStream, stopMediaStream } from "./camera";
import { loadMindARThree, type MindARThreeInstance, withTimeout } from "./mindRuntime";
import { hasCurrentMindTarget, MIND_AR_COMPILER_VERSION } from "./mindVersion";
import { createRuntimeLayerMesh, type RuntimeLayerMesh } from "./runtimeLayerMesh";

export type ProjectARDiagnostics = {
  camera?: string;
  runtime?: string;
  mindarStart?: string;
  mindTarget?: string;
  mindCompilerVersion?: string;
  layers?: string;
  layersLoaded?: string;
  imageTargetSrcMode?: string;
  targetFoundCount?: string;
};

export type ProjectARSession = {
  stop: () => void;
};

type ProjectARSessionOptions = {
  container: HTMLElement;
  project: ARProject;
  startTimeoutMs?: number;
  onStatus?: (status: string) => void;
  onDiagnostics?: (diagnostics: ProjectARDiagnostics) => void;
  onTargetFound?: () => void;
  onTargetLost?: () => void;
};

const disposeLayerMesh = (mesh: RuntimeLayerMesh) => {
  mesh.userData.video?.pause();
  mesh.geometry.dispose();
  mesh.material.dispose();
};

const playLayerVideos = (meshes: RuntimeLayerMesh[]) => {
  meshes.forEach((mesh) => {
    if (mesh.userData.video) void mesh.userData.video.play().catch(() => undefined);
  });
};

const pauseLayerVideos = (meshes: RuntimeLayerMesh[]) => {
  meshes.forEach((mesh) => mesh.userData.video?.pause());
};

export const startProjectMindARSession = async ({
  container,
  project,
  startTimeoutMs = 60000,
  onStatus,
  onDiagnostics,
  onTargetFound,
  onTargetLost,
}: ProjectARSessionOptions): Promise<ProjectARSession> => {
  if (!project.mindTargetUrl) throw new Error("This project does not have a .mind target yet");
  if (!hasCurrentMindTarget(project)) {
    throw new Error(`This .mind target was not generated by ${MIND_AR_COMPILER_VERSION}. Please rebuild .mind in the Editor.`);
  }

  let mindarThree: MindARThreeInstance | null = null;
  let meshes: RuntimeLayerMesh[] = [];
  let targetVisible = false;
  let targetFoundCount = 0;
  let layersPromise: Promise<RuntimeLayerMesh[]> | null = null;

  const stop = () => {
    pauseLayerVideos(meshes);
    meshes.forEach(disposeLayerMesh);
    meshes = [];

    try {
      mindarThree?.renderer.setAnimationLoop(null);
      mindarThree?.stop();
    } catch {
      // MindAR can throw if stop is called while startup is still settling.
    }
    mindarThree = null;
  };

  try {
    onDiagnostics?.({ mindCompilerVersion: project.mindCompilerVersion ?? "missing" });
    onStatus?.("準備使用 .mind URL");
    onDiagnostics?.({ mindTarget: "direct-url", imageTargetSrcMode: "direct-url", targetFoundCount: "0", layersLoaded: "0" });

    onStatus?.("檢查手機相機權限");
    onDiagnostics?.({ camera: "requesting native getUserMedia", mindarStart: "not started" });
    const stream = await withTimeout(requestCameraStream(), 10000, "Camera permission check timed out after 10 seconds");
    const [track] = stream.getVideoTracks();
    onDiagnostics?.({ camera: `granted: ${track?.label || "camera stream"}` });
    stopMediaStream(stream);

    onStatus?.("載入 MindAR 官方 Three.js runtime");
    onDiagnostics?.({ runtime: "loading" });
    const runtime = await loadMindARThree();
    onDiagnostics?.({ runtime: `loaded: ${runtime.source}` });

    onStatus?.("建立 MindAR 圖片追蹤場景");
    mindarThree = new runtime.MindARThree({
      container,
      imageTargetSrc: project.mindTargetUrl,
      maxTrack: 1,
      uiLoading: "yes",
      uiScanning: "yes",
      uiError: "yes",
    });

    const { renderer, scene, camera } = mindarThree;
    const anchor = mindarThree.addAnchor(0);
    const orderedLayers = [...project.layers].sort((left, right) => left.order - right.order);
    const ensureLayersLoaded = async () => {
      if (!layersPromise) {
        onStatus?.(`已辨識 Trigger Image，載入 ${project.layers.length} 個專案圖層`);
        onDiagnostics?.({ layers: "loading", layersLoaded: `0/${project.layers.length}` });
        layersPromise = Promise.all(
          orderedLayers.map((layer) =>
            createRuntimeLayerMesh(runtime.THREE, layer).catch((error) => {
              console.warn(`Unable to load AR layer ${layer.id}`, error);
              return null;
            }),
          ),
        ).then((loadedMeshes) => {
          meshes = loadedMeshes.filter((mesh): mesh is RuntimeLayerMesh => Boolean(mesh));
          meshes.forEach((mesh) => anchor.group.add(mesh));
          onDiagnostics?.({ layers: `${meshes.length}/${project.layers.length} loaded`, layersLoaded: `${meshes.length}/${project.layers.length}` });
          return meshes;
        });
      }

      const loadedMeshes = await layersPromise;
      if (targetVisible) {
        playLayerVideos(loadedMeshes);
        onStatus?.(`已辨識 Trigger Image，顯示 ${loadedMeshes.length} 個 AR 圖層`);
      }
    };

    anchor.onTargetFound = () => {
      targetVisible = true;
      targetFoundCount += 1;
      onDiagnostics?.({ targetFoundCount: String(targetFoundCount) });
      void ensureLayersLoaded().catch((error) => {
        console.error(error);
        onDiagnostics?.({ layers: `failed: ${error instanceof Error ? error.message : String(error)}` });
        onStatus?.("已辨識 Trigger Image，但圖層載入失敗");
      });
      onTargetFound?.();
    };
    anchor.onTargetLost = () => {
      onStatus?.("追蹤暫停，請重新對準 Trigger Image");
      targetVisible = false;
      pauseLayerVideos(meshes);
      onTargetLost?.();
    };

    onStatus?.("啟動相機與圖片辨識");
    onDiagnostics?.({ mindarStart: "starting" });
    await withTimeout(mindarThree.start(), startTimeoutMs, `MindAR start timeout after ${Math.round(startTimeoutMs / 1000)} seconds`);
    onDiagnostics?.({ mindarStart: "resolved" });

    renderer.setAnimationLoop(() => renderer.render(scene, camera));
    onStatus?.("相機已啟動，請掃描 Trigger Image");

    return { stop };
  } catch (error) {
    stop();
    if (error instanceof DOMException) {
      const message = cameraErrorMessage(error);
      onDiagnostics?.({ camera: `failed: ${message}` });
      throw new Error(message);
    }
    throw error;
  }
};
