import type { ARProject } from "../types/project";
import type * as THREE from "three";
import { cameraErrorMessage, requestCameraStream, stopMediaStream } from "./camera";
import { loadMindARThree, type MindARThreeInstance, withTimeout } from "./mindRuntime";
import { hasCurrentMindTarget, MIND_AR_COMPILER_VERSION } from "./mindVersion";
import { createRuntimeLayerMesh, type RuntimeLayerMesh } from "./runtimeLayerMesh";

export type ProjectARDiagnostics = {
  camera?: string;
  runtime?: string;
  mindarStart?: string;
  mindTarget?: string;
  mindCompilerVersion?: string;
  layers?: string;
  layersLoaded?: string;
  imageTargetSrcMode?: string;
  targetFoundCount?: string;
  depthMode?: string;
};

export type ProjectARSession = {
  stop: () => void;
};

type ProjectARSessionOptions = {
  container: HTMLElement;
  project: ARProject;
  startTimeoutMs?: number;
  onStatus?: (status: string) => void;
  onDiagnostics?: (diagnostics: ProjectARDiagnostics) => void;
  onTargetFound?: () => void;
  onTargetLost?: () => void;
};

const VIEWER_DEPTH_BOOST = 2.8;
const VIEWER_MINIMUM_DEPTH_STEP = 0.11;
const TRACKING_POSITION_SMOOTHING = 0.22;
const TRACKING_ROTATION_SMOOTHING = 0.18;
const TRACKING_SCALE_SMOOTHING = 0.2;
const TRACKING_LOST_HOLD_MS = 320;

const disposeLayerMesh = (mesh: RuntimeLayerMesh) => {
  mesh.userData.video?.pause();
  mesh.geometry.dispose();
  mesh.material.dispose();
};

const playLayerVideos = (meshes: RuntimeLayerMesh[]) => {
  meshes.forEach((mesh) => {
    if (mesh.userData.video) void mesh.userData.video.play().catch(() => undefined);
  });
};

const pauseLayerVideos = (meshes: RuntimeLayerMesh[]) => {
  meshes.forEach((mesh) => mesh.userData.video?.pause());
};

export const startProjectMindARSession = async ({
  container,
  project,
  startTimeoutMs = 60000,
  onStatus,
  onDiagnostics,
  onTargetFound,
  onTargetLost,
}: ProjectARSessionOptions): Promise<ProjectARSession> => {
  if (!project.mindTargetUrl) throw new Error("This project does not have a .mind target yet");
  if (!hasCurrentMindTarget(project)) {
    throw new Error(`This .mind target was not generated by ${MIND_AR_COMPILER_VERSION}. Please rebuild .mind in the Editor.`);
  }

  let mindarThree: MindARThreeInstance | null = null;
  let meshes: RuntimeLayerMesh[] = [];
  let stableGroup: THREE.Group | null = null;
  let targetVisible = false;
  let firstStableFrame = true;
  let lostAt = 0;
  let pausedAfterLost = false;
  let targetFoundCount = 0;
  let layersPromise: Promise<RuntimeLayerMesh[]> | null = null;

  const stop = () => {
    pauseLayerVideos(meshes);
    meshes.forEach(disposeLayerMesh);
    meshes = [];
    stableGroup?.parent?.remove(stableGroup);
    stableGroup = null;

    try {
      mindarThree?.renderer.setAnimationLoop(null);
      mindarThree?.stop();
    } catch {
      // MindAR can throw if stop is called while startup is still settling.
    }
    mindarThree = null;
  };

  try {
    onDiagnostics?.({ mindCompilerVersion: project.mindCompilerVersion ?? "missing" });
    onStatus?.("準備使用 .mind URL");
    onDiagnostics?.({
      mindTarget: "direct-url",
      imageTargetSrcMode: "direct-url",
      targetFoundCount: "0",
      layersLoaded: "0",
      depthMode: `${VIEWER_DEPTH_BOOST}x depth, min ${VIEWER_MINIMUM_DEPTH_STEP}, smoothing on`,
    });

    onStatus?.("檢查手機相機權限");
    onDiagnostics?.({ camera: "requesting native getUserMedia", mindarStart: "not started" });
    const stream = await withTimeout(requestCameraStream(), 10000, "Camera permission check timed out after 10 seconds");
    const [track] = stream.getVideoTracks();
    onDiagnostics?.({ camera: `granted: ${track?.label || "camera stream"}` });
    stopMediaStream(stream);

    onStatus?.("載入 MindAR Three.js runtime");
    onDiagnostics?.({ runtime: "loading" });
    const runtime = await loadMindARThree();
    onDiagnostics?.({ runtime: `loaded: ${runtime.source}` });

    onStatus?.("建立 MindAR 影像追蹤場景");
    mindarThree = new runtime.MindARThree({
      container,
      imageTargetSrc: project.mindTargetUrl,
      maxTrack: 1,
      uiLoading: "yes",
      uiScanning: "yes",
      uiError: "yes",
    });

    const { renderer, scene, camera } = mindarThree;
    const anchor = mindarThree.addAnchor(0);
    stableGroup = new runtime.THREE.Group();
    stableGroup.visible = false;
    scene.add(stableGroup);
    const orderedLayers = [...project.layers].sort((left, right) => left.order - right.order);
    const ensureLayersLoaded = async () => {
      if (!layersPromise) {
        onStatus?.(`已辨識 Trigger Image，載入 ${project.layers.length} 個 AR 圖層`);
        onDiagnostics?.({ layers: "loading", layersLoaded: `0/${project.layers.length}` });
        layersPromise = Promise.all(
          orderedLayers.map((layer, index) =>
            createRuntimeLayerMesh(runtime.THREE, layer, {
              depthBoost: VIEWER_DEPTH_BOOST,
              minimumDepth: (index + 1) * VIEWER_MINIMUM_DEPTH_STEP,
            }).catch((error) => {
              console.warn(`Unable to load AR layer ${layer.id}`, error);
              return null;
            }),
          ),
        ).then((loadedMeshes) => {
          meshes = loadedMeshes.filter((mesh): mesh is RuntimeLayerMesh => Boolean(mesh));
          meshes.forEach((mesh) => stableGroup?.add(mesh));
          onDiagnostics?.({ layers: `${meshes.length}/${project.layers.length} loaded`, layersLoaded: `${meshes.length}/${project.layers.length}` });
          return meshes;
        });
      }

      const loadedMeshes = await layersPromise;
      if (targetVisible) {
        playLayerVideos(loadedMeshes);
        onStatus?.(`已辨識 Trigger Image，顯示 ${loadedMeshes.length} 個 AR 圖層`);
      }
    };

    anchor.onTargetFound = () => {
      targetVisible = true;
      firstStableFrame = true;
      pausedAfterLost = false;
      if (stableGroup) stableGroup.visible = true;
      targetFoundCount += 1;
      onDiagnostics?.({ targetFoundCount: String(targetFoundCount) });
      void ensureLayersLoaded().catch((error) => {
        console.error(error);
        onDiagnostics?.({ layers: `failed: ${error instanceof Error ? error.message : String(error)}` });
        onStatus?.("已辨識 Trigger Image，但圖層載入失敗");
      });
      onTargetFound?.();
    };
    anchor.onTargetLost = () => {
      onStatus?.("追蹤暫停，請重新對準 Trigger Image");
      targetVisible = false;
      lostAt = performance.now();
      onTargetLost?.();
    };

    onStatus?.("啟動相機與圖片辨識");
    onDiagnostics?.({ mindarStart: "starting" });
    await withTimeout(mindarThree.start(), startTimeoutMs, `MindAR start timeout after ${Math.round(startTimeoutMs / 1000)} seconds`);
    onDiagnostics?.({ mindarStart: "resolved" });

    renderer.setAnimationLoop(() => {
      if (stableGroup) {
        if (targetVisible) {
          if (firstStableFrame) {
            stableGroup.position.copy(anchor.group.position);
            stableGroup.quaternion.copy(anchor.group.quaternion);
            stableGroup.scale.copy(anchor.group.scale);
            firstStableFrame = false;
          } else {
            stableGroup.position.lerp(anchor.group.position, TRACKING_POSITION_SMOOTHING);
            stableGroup.quaternion.slerp(anchor.group.quaternion, TRACKING_ROTATION_SMOOTHING);
            stableGroup.scale.lerp(anchor.group.scale, TRACKING_SCALE_SMOOTHING);
          }
          stableGroup.visible = true;
        } else if (performance.now() - lostAt > TRACKING_LOST_HOLD_MS) {
          stableGroup.visible = false;
          if (!pausedAfterLost) {
            pauseLayerVideos(meshes);
            pausedAfterLost = true;
          }
        }
      }
      renderer.render(scene, camera);
    });
    onStatus?.("相機已啟動，請掃描 Trigger Image");

    return { stop };
  } catch (error) {
    stop();
    if (error instanceof DOMException) {
      const message = cameraErrorMessage(error);
      onDiagnostics?.({ camera: `failed: ${message}` });
      throw new Error(message);
    }
    throw error;
  }
};
